### PR TITLE
Update URLs to HTTPS

### PR DESCRIPTION
**Pull request by bobapple**

### CODE REVIEW

**Review by htriem — APPROVED** [review]
LGTM! 👍

**Comment by julianbrost** [comment]
Some of the RPM directories have `icinga-rpm-release` packages in there. Have you checked if any of these needs an update?

**Comment by julianbrost** [comment]
> As far as I can tell they all are already?

My point was to ask if anyone has checked this.

**Comment by htriem** [comment]
Oh, okay! Yes, I did :D

**Pull request merged**
